
## Multi Stage Build 

FROM node:20.18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./  

RUN npm ci

COPY . .  

RUN npm run build  

# Produktionsumgebung

FROM nginx:stable-alpine 

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]